
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Employer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Employer
 * 
 */
export type EmployerModel = runtime.Types.Result.DefaultSelection<Prisma.$EmployerPayload>

export type AggregateEmployer = {
  _count: EmployerCountAggregateOutputType | null
  _min: EmployerMinAggregateOutputType | null
  _max: EmployerMaxAggregateOutputType | null
}

export type EmployerMinAggregateOutputType = {
  id: string | null
  name: string | null
  phone: string | null
  companyName: string | null
  email: string | null
  password: string | null
  provider: string | null
  bio: string | null
  createdAt: Date | null
}

export type EmployerMaxAggregateOutputType = {
  id: string | null
  name: string | null
  phone: string | null
  companyName: string | null
  email: string | null
  password: string | null
  provider: string | null
  bio: string | null
  createdAt: Date | null
}

export type EmployerCountAggregateOutputType = {
  id: number
  name: number
  phone: number
  companyName: number
  email: number
  password: number
  provider: number
  bio: number
  createdAt: number
  _all: number
}


export type EmployerMinAggregateInputType = {
  id?: true
  name?: true
  phone?: true
  companyName?: true
  email?: true
  password?: true
  provider?: true
  bio?: true
  createdAt?: true
}

export type EmployerMaxAggregateInputType = {
  id?: true
  name?: true
  phone?: true
  companyName?: true
  email?: true
  password?: true
  provider?: true
  bio?: true
  createdAt?: true
}

export type EmployerCountAggregateInputType = {
  id?: true
  name?: true
  phone?: true
  companyName?: true
  email?: true
  password?: true
  provider?: true
  bio?: true
  createdAt?: true
  _all?: true
}

export type EmployerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Employer to aggregate.
   */
  where?: Prisma.EmployerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Employers to fetch.
   */
  orderBy?: Prisma.EmployerOrderByWithRelationInput | Prisma.EmployerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmployerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Employers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Employers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Employers
  **/
  _count?: true | EmployerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmployerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmployerMaxAggregateInputType
}

export type GetEmployerAggregateType<T extends EmployerAggregateArgs> = {
      [P in keyof T & keyof AggregateEmployer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmployer[P]>
    : Prisma.GetScalarType<T[P], AggregateEmployer[P]>
}




export type EmployerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmployerWhereInput
  orderBy?: Prisma.EmployerOrderByWithAggregationInput | Prisma.EmployerOrderByWithAggregationInput[]
  by: Prisma.EmployerScalarFieldEnum[] | Prisma.EmployerScalarFieldEnum
  having?: Prisma.EmployerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmployerCountAggregateInputType | true
  _min?: EmployerMinAggregateInputType
  _max?: EmployerMaxAggregateInputType
}

export type EmployerGroupByOutputType = {
  id: string
  name: string
  phone: string
  companyName: string
  email: string
  password: string | null
  provider: string
  bio: string | null
  createdAt: Date
  _count: EmployerCountAggregateOutputType | null
  _min: EmployerMinAggregateOutputType | null
  _max: EmployerMaxAggregateOutputType | null
}

type GetEmployerGroupByPayload<T extends EmployerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmployerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmployerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmployerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmployerGroupByOutputType[P]>
      }
    >
  >



export type EmployerWhereInput = {
  AND?: Prisma.EmployerWhereInput | Prisma.EmployerWhereInput[]
  OR?: Prisma.EmployerWhereInput[]
  NOT?: Prisma.EmployerWhereInput | Prisma.EmployerWhereInput[]
  id?: Prisma.StringFilter<"Employer"> | string
  name?: Prisma.StringFilter<"Employer"> | string
  phone?: Prisma.StringFilter<"Employer"> | string
  companyName?: Prisma.StringFilter<"Employer"> | string
  email?: Prisma.StringFilter<"Employer"> | string
  password?: Prisma.StringNullableFilter<"Employer"> | string | null
  provider?: Prisma.StringFilter<"Employer"> | string
  bio?: Prisma.StringNullableFilter<"Employer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Employer"> | Date | string
  jobs?: Prisma.JobListRelationFilter
}

export type EmployerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  provider?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  jobs?: Prisma.JobOrderByRelationAggregateInput
}

export type EmployerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.EmployerWhereInput | Prisma.EmployerWhereInput[]
  OR?: Prisma.EmployerWhereInput[]
  NOT?: Prisma.EmployerWhereInput | Prisma.EmployerWhereInput[]
  name?: Prisma.StringFilter<"Employer"> | string
  phone?: Prisma.StringFilter<"Employer"> | string
  companyName?: Prisma.StringFilter<"Employer"> | string
  password?: Prisma.StringNullableFilter<"Employer"> | string | null
  provider?: Prisma.StringFilter<"Employer"> | string
  bio?: Prisma.StringNullableFilter<"Employer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Employer"> | Date | string
  jobs?: Prisma.JobListRelationFilter
}, "id" | "email">

export type EmployerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  provider?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.EmployerCountOrderByAggregateInput
  _max?: Prisma.EmployerMaxOrderByAggregateInput
  _min?: Prisma.EmployerMinOrderByAggregateInput
}

export type EmployerScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmployerScalarWhereWithAggregatesInput | Prisma.EmployerScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmployerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmployerScalarWhereWithAggregatesInput | Prisma.EmployerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Employer"> | string
  name?: Prisma.StringWithAggregatesFilter<"Employer"> | string
  phone?: Prisma.StringWithAggregatesFilter<"Employer"> | string
  companyName?: Prisma.StringWithAggregatesFilter<"Employer"> | string
  email?: Prisma.StringWithAggregatesFilter<"Employer"> | string
  password?: Prisma.StringNullableWithAggregatesFilter<"Employer"> | string | null
  provider?: Prisma.StringWithAggregatesFilter<"Employer"> | string
  bio?: Prisma.StringNullableWithAggregatesFilter<"Employer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Employer"> | Date | string
}

export type EmployerCreateInput = {
  id?: string
  name: string
  phone: string
  companyName: string
  email: string
  password?: string | null
  provider?: string
  bio?: string | null
  createdAt?: Date | string
  jobs?: Prisma.JobCreateNestedManyWithoutEmployerInput
}

export type EmployerUncheckedCreateInput = {
  id?: string
  name: string
  phone: string
  companyName: string
  email: string
  password?: string | null
  provider?: string
  bio?: string | null
  createdAt?: Date | string
  jobs?: Prisma.JobUncheckedCreateNestedManyWithoutEmployerInput
}

export type EmployerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jobs?: Prisma.JobUpdateManyWithoutEmployerNestedInput
}

export type EmployerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jobs?: Prisma.JobUncheckedUpdateManyWithoutEmployerNestedInput
}

export type EmployerCreateManyInput = {
  id?: string
  name: string
  phone: string
  companyName: string
  email: string
  password?: string | null
  provider?: string
  bio?: string | null
  createdAt?: Date | string
}

export type EmployerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EmployerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EmployerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EmployerScalarRelationFilter = {
  is?: Prisma.EmployerWhereInput
  isNot?: Prisma.EmployerWhereInput
}

export type EmployerCreateNestedOneWithoutJobsInput = {
  create?: Prisma.XOR<Prisma.EmployerCreateWithoutJobsInput, Prisma.EmployerUncheckedCreateWithoutJobsInput>
  connectOrCreate?: Prisma.EmployerCreateOrConnectWithoutJobsInput
  connect?: Prisma.EmployerWhereUniqueInput
}

export type EmployerUpdateOneRequiredWithoutJobsNestedInput = {
  create?: Prisma.XOR<Prisma.EmployerCreateWithoutJobsInput, Prisma.EmployerUncheckedCreateWithoutJobsInput>
  connectOrCreate?: Prisma.EmployerCreateOrConnectWithoutJobsInput
  upsert?: Prisma.EmployerUpsertWithoutJobsInput
  connect?: Prisma.EmployerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmployerUpdateToOneWithWhereWithoutJobsInput, Prisma.EmployerUpdateWithoutJobsInput>, Prisma.EmployerUncheckedUpdateWithoutJobsInput>
}

export type EmployerCreateWithoutJobsInput = {
  id?: string
  name: string
  phone: string
  companyName: string
  email: string
  password?: string | null
  provider?: string
  bio?: string | null
  createdAt?: Date | string
}

export type EmployerUncheckedCreateWithoutJobsInput = {
  id?: string
  name: string
  phone: string
  companyName: string
  email: string
  password?: string | null
  provider?: string
  bio?: string | null
  createdAt?: Date | string
}

export type EmployerCreateOrConnectWithoutJobsInput = {
  where: Prisma.EmployerWhereUniqueInput
  create: Prisma.XOR<Prisma.EmployerCreateWithoutJobsInput, Prisma.EmployerUncheckedCreateWithoutJobsInput>
}

export type EmployerUpsertWithoutJobsInput = {
  update: Prisma.XOR<Prisma.EmployerUpdateWithoutJobsInput, Prisma.EmployerUncheckedUpdateWithoutJobsInput>
  create: Prisma.XOR<Prisma.EmployerCreateWithoutJobsInput, Prisma.EmployerUncheckedCreateWithoutJobsInput>
  where?: Prisma.EmployerWhereInput
}

export type EmployerUpdateToOneWithWhereWithoutJobsInput = {
  where?: Prisma.EmployerWhereInput
  data: Prisma.XOR<Prisma.EmployerUpdateWithoutJobsInput, Prisma.EmployerUncheckedUpdateWithoutJobsInput>
}

export type EmployerUpdateWithoutJobsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployerUncheckedUpdateWithoutJobsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EmployerCountOutputType
 */

export type EmployerCountOutputType = {
  jobs: number
}

export type EmployerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | EmployerCountOutputTypeCountJobsArgs
}

/**
 * EmployerCountOutputType without action
 */
export type EmployerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployerCountOutputType
   */
  select?: Prisma.EmployerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EmployerCountOutputType without action
 */
export type EmployerCountOutputTypeCountJobsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JobWhereInput
}


export type EmployerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  phone?: boolean
  companyName?: boolean
  email?: boolean
  password?: boolean
  provider?: boolean
  bio?: boolean
  createdAt?: boolean
  jobs?: boolean | Prisma.Employer$jobsArgs<ExtArgs>
  _count?: boolean | Prisma.EmployerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employer"]>

export type EmployerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  phone?: boolean
  companyName?: boolean
  email?: boolean
  password?: boolean
  provider?: boolean
  bio?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["employer"]>

export type EmployerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  phone?: boolean
  companyName?: boolean
  email?: boolean
  password?: boolean
  provider?: boolean
  bio?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["employer"]>

export type EmployerSelectScalar = {
  id?: boolean
  name?: boolean
  phone?: boolean
  companyName?: boolean
  email?: boolean
  password?: boolean
  provider?: boolean
  bio?: boolean
  createdAt?: boolean
}

export type EmployerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "phone" | "companyName" | "email" | "password" | "provider" | "bio" | "createdAt", ExtArgs["result"]["employer"]>
export type EmployerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.Employer$jobsArgs<ExtArgs>
  _count?: boolean | Prisma.EmployerCountOutputTypeDefaultArgs<ExtArgs>
}
export type EmployerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type EmployerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $EmployerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Employer"
  objects: {
    jobs: Prisma.$JobPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    phone: string
    companyName: string
    email: string
    password: string | null
    provider: string
    bio: string | null
    createdAt: Date
  }, ExtArgs["result"]["employer"]>
  composites: {}
}

export type EmployerGetPayload<S extends boolean | null | undefined | EmployerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmployerPayload, S>

export type EmployerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmployerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmployerCountAggregateInputType | true
  }

export interface EmployerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Employer'], meta: { name: 'Employer' } }
  /**
   * Find zero or one Employer that matches the filter.
   * @param {EmployerFindUniqueArgs} args - Arguments to find a Employer
   * @example
   * // Get one Employer
   * const employer = await prisma.employer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmployerFindUniqueArgs>(args: Prisma.SelectSubset<T, EmployerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmployerClient<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Employer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmployerFindUniqueOrThrowArgs} args - Arguments to find a Employer
   * @example
   * // Get one Employer
   * const employer = await prisma.employer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmployerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmployerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmployerClient<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Employer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployerFindFirstArgs} args - Arguments to find a Employer
   * @example
   * // Get one Employer
   * const employer = await prisma.employer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmployerFindFirstArgs>(args?: Prisma.SelectSubset<T, EmployerFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmployerClient<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Employer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployerFindFirstOrThrowArgs} args - Arguments to find a Employer
   * @example
   * // Get one Employer
   * const employer = await prisma.employer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmployerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmployerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmployerClient<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Employers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Employers
   * const employers = await prisma.employer.findMany()
   * 
   * // Get first 10 Employers
   * const employers = await prisma.employer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const employerWithIdOnly = await prisma.employer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmployerFindManyArgs>(args?: Prisma.SelectSubset<T, EmployerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Employer.
   * @param {EmployerCreateArgs} args - Arguments to create a Employer.
   * @example
   * // Create one Employer
   * const Employer = await prisma.employer.create({
   *   data: {
   *     // ... data to create a Employer
   *   }
   * })
   * 
   */
  create<T extends EmployerCreateArgs>(args: Prisma.SelectSubset<T, EmployerCreateArgs<ExtArgs>>): Prisma.Prisma__EmployerClient<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Employers.
   * @param {EmployerCreateManyArgs} args - Arguments to create many Employers.
   * @example
   * // Create many Employers
   * const employer = await prisma.employer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmployerCreateManyArgs>(args?: Prisma.SelectSubset<T, EmployerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Employers and returns the data saved in the database.
   * @param {EmployerCreateManyAndReturnArgs} args - Arguments to create many Employers.
   * @example
   * // Create many Employers
   * const employer = await prisma.employer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Employers and only return the `id`
   * const employerWithIdOnly = await prisma.employer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmployerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmployerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Employer.
   * @param {EmployerDeleteArgs} args - Arguments to delete one Employer.
   * @example
   * // Delete one Employer
   * const Employer = await prisma.employer.delete({
   *   where: {
   *     // ... filter to delete one Employer
   *   }
   * })
   * 
   */
  delete<T extends EmployerDeleteArgs>(args: Prisma.SelectSubset<T, EmployerDeleteArgs<ExtArgs>>): Prisma.Prisma__EmployerClient<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Employer.
   * @param {EmployerUpdateArgs} args - Arguments to update one Employer.
   * @example
   * // Update one Employer
   * const employer = await prisma.employer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmployerUpdateArgs>(args: Prisma.SelectSubset<T, EmployerUpdateArgs<ExtArgs>>): Prisma.Prisma__EmployerClient<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Employers.
   * @param {EmployerDeleteManyArgs} args - Arguments to filter Employers to delete.
   * @example
   * // Delete a few Employers
   * const { count } = await prisma.employer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmployerDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmployerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Employers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Employers
   * const employer = await prisma.employer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmployerUpdateManyArgs>(args: Prisma.SelectSubset<T, EmployerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Employers and returns the data updated in the database.
   * @param {EmployerUpdateManyAndReturnArgs} args - Arguments to update many Employers.
   * @example
   * // Update many Employers
   * const employer = await prisma.employer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Employers and only return the `id`
   * const employerWithIdOnly = await prisma.employer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmployerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmployerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Employer.
   * @param {EmployerUpsertArgs} args - Arguments to update or create a Employer.
   * @example
   * // Update or create a Employer
   * const employer = await prisma.employer.upsert({
   *   create: {
   *     // ... data to create a Employer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Employer we want to update
   *   }
   * })
   */
  upsert<T extends EmployerUpsertArgs>(args: Prisma.SelectSubset<T, EmployerUpsertArgs<ExtArgs>>): Prisma.Prisma__EmployerClient<runtime.Types.Result.GetResult<Prisma.$EmployerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Employers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployerCountArgs} args - Arguments to filter Employers to count.
   * @example
   * // Count the number of Employers
   * const count = await prisma.employer.count({
   *   where: {
   *     // ... the filter for the Employers we want to count
   *   }
   * })
  **/
  count<T extends EmployerCountArgs>(
    args?: Prisma.Subset<T, EmployerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmployerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Employer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmployerAggregateArgs>(args: Prisma.Subset<T, EmployerAggregateArgs>): Prisma.PrismaPromise<GetEmployerAggregateType<T>>

  /**
   * Group by Employer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmployerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmployerGroupByArgs['orderBy'] }
      : { orderBy?: EmployerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmployerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmployerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Employer model
 */
readonly fields: EmployerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Employer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmployerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  jobs<T extends Prisma.Employer$jobsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Employer$jobsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Employer model
 */
export interface EmployerFieldRefs {
  readonly id: Prisma.FieldRef<"Employer", 'String'>
  readonly name: Prisma.FieldRef<"Employer", 'String'>
  readonly phone: Prisma.FieldRef<"Employer", 'String'>
  readonly companyName: Prisma.FieldRef<"Employer", 'String'>
  readonly email: Prisma.FieldRef<"Employer", 'String'>
  readonly password: Prisma.FieldRef<"Employer", 'String'>
  readonly provider: Prisma.FieldRef<"Employer", 'String'>
  readonly bio: Prisma.FieldRef<"Employer", 'String'>
  readonly createdAt: Prisma.FieldRef<"Employer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Employer findUnique
 */
export type EmployerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * Filter, which Employer to fetch.
   */
  where: Prisma.EmployerWhereUniqueInput
}

/**
 * Employer findUniqueOrThrow
 */
export type EmployerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * Filter, which Employer to fetch.
   */
  where: Prisma.EmployerWhereUniqueInput
}

/**
 * Employer findFirst
 */
export type EmployerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * Filter, which Employer to fetch.
   */
  where?: Prisma.EmployerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Employers to fetch.
   */
  orderBy?: Prisma.EmployerOrderByWithRelationInput | Prisma.EmployerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Employers.
   */
  cursor?: Prisma.EmployerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Employers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Employers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Employers.
   */
  distinct?: Prisma.EmployerScalarFieldEnum | Prisma.EmployerScalarFieldEnum[]
}

/**
 * Employer findFirstOrThrow
 */
export type EmployerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * Filter, which Employer to fetch.
   */
  where?: Prisma.EmployerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Employers to fetch.
   */
  orderBy?: Prisma.EmployerOrderByWithRelationInput | Prisma.EmployerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Employers.
   */
  cursor?: Prisma.EmployerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Employers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Employers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Employers.
   */
  distinct?: Prisma.EmployerScalarFieldEnum | Prisma.EmployerScalarFieldEnum[]
}

/**
 * Employer findMany
 */
export type EmployerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * Filter, which Employers to fetch.
   */
  where?: Prisma.EmployerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Employers to fetch.
   */
  orderBy?: Prisma.EmployerOrderByWithRelationInput | Prisma.EmployerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Employers.
   */
  cursor?: Prisma.EmployerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Employers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Employers.
   */
  skip?: number
  distinct?: Prisma.EmployerScalarFieldEnum | Prisma.EmployerScalarFieldEnum[]
}

/**
 * Employer create
 */
export type EmployerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * The data needed to create a Employer.
   */
  data: Prisma.XOR<Prisma.EmployerCreateInput, Prisma.EmployerUncheckedCreateInput>
}

/**
 * Employer createMany
 */
export type EmployerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Employers.
   */
  data: Prisma.EmployerCreateManyInput | Prisma.EmployerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Employer createManyAndReturn
 */
export type EmployerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * The data used to create many Employers.
   */
  data: Prisma.EmployerCreateManyInput | Prisma.EmployerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Employer update
 */
export type EmployerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * The data needed to update a Employer.
   */
  data: Prisma.XOR<Prisma.EmployerUpdateInput, Prisma.EmployerUncheckedUpdateInput>
  /**
   * Choose, which Employer to update.
   */
  where: Prisma.EmployerWhereUniqueInput
}

/**
 * Employer updateMany
 */
export type EmployerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Employers.
   */
  data: Prisma.XOR<Prisma.EmployerUpdateManyMutationInput, Prisma.EmployerUncheckedUpdateManyInput>
  /**
   * Filter which Employers to update
   */
  where?: Prisma.EmployerWhereInput
  /**
   * Limit how many Employers to update.
   */
  limit?: number
}

/**
 * Employer updateManyAndReturn
 */
export type EmployerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * The data used to update Employers.
   */
  data: Prisma.XOR<Prisma.EmployerUpdateManyMutationInput, Prisma.EmployerUncheckedUpdateManyInput>
  /**
   * Filter which Employers to update
   */
  where?: Prisma.EmployerWhereInput
  /**
   * Limit how many Employers to update.
   */
  limit?: number
}

/**
 * Employer upsert
 */
export type EmployerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * The filter to search for the Employer to update in case it exists.
   */
  where: Prisma.EmployerWhereUniqueInput
  /**
   * In case the Employer found by the `where` argument doesn't exist, create a new Employer with this data.
   */
  create: Prisma.XOR<Prisma.EmployerCreateInput, Prisma.EmployerUncheckedCreateInput>
  /**
   * In case the Employer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmployerUpdateInput, Prisma.EmployerUncheckedUpdateInput>
}

/**
 * Employer delete
 */
export type EmployerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
  /**
   * Filter which Employer to delete.
   */
  where: Prisma.EmployerWhereUniqueInput
}

/**
 * Employer deleteMany
 */
export type EmployerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Employers to delete
   */
  where?: Prisma.EmployerWhereInput
  /**
   * Limit how many Employers to delete.
   */
  limit?: number
}

/**
 * Employer.jobs
 */
export type Employer$jobsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Job
   */
  select?: Prisma.JobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Job
   */
  omit?: Prisma.JobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobInclude<ExtArgs> | null
  where?: Prisma.JobWhereInput
  orderBy?: Prisma.JobOrderByWithRelationInput | Prisma.JobOrderByWithRelationInput[]
  cursor?: Prisma.JobWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.JobScalarFieldEnum | Prisma.JobScalarFieldEnum[]
}

/**
 * Employer without action
 */
export type EmployerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employer
   */
  select?: Prisma.EmployerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employer
   */
  omit?: Prisma.EmployerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployerInclude<ExtArgs> | null
}
